{
  page: 1;  
  results: [
    {       
      adult: false,
      backdrop_path: '/jsoz1HlxczSuTx0mDl2h0lxy36l.jpg',
      id: 616037,
      title: 'Thor: Love and Thunder',
      original_language: 'en',
      original_title: 'Thor: Love and Thunder',
      overview: 'After his retirement is interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods, Thor Odinson enlists the help of King Valkyrie, Korg, and ex-girlfriend Jane Foster, who now wields Mjolnir as the Mighty Thor. Together they embark upon a harrowing cosmic adventure to uncover the mystery of the God Butcher’s vengeance and stop him before it’s too late.',
      poster_path: '/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg',
      media_type: 'movie',
      genre_ids: [Array],
      popularity: 5906.414,
      release_date: '2022-07-06',
      video: false,
      vote_average: 6.811,
      vote_count: 3062
    },
    {
      adult: false,
      backdrop_path: '/lv4mA4jOnRSQCkmDYUyZ8ON43Dc.jpg',
      id: 532639,
      title: 'Pinocchio',
      original_language: 'en',
      original_title: 'Pinocchio',
      overview: 'A wooden puppet embarks on a thrilling adventure to become a real boy.',
      poster_path: '/g8sclIV4gj1TZqUpnL82hKOTK3B.jpg',
      media_type: 'movie',
      genre_ids: [Array],
      popularity: 1341.22,
      release_date: '2022-09-07',
      video: false,
      vote_average: 6.837,
      vote_count: 313
    },
    {
      adult: false,
      backdrop_path: '/2k9tBql5GYH328Krj66tDT9LtFZ.jpg',
      id: 760741,
      title: 'Beast',
      original_language: 'en',
      original_title: 'Beast',
      overview: 'A recently widowed man and his two teenage daughters travel to a game reserve in South Africa. However, their journey of healing soon turns into a fight for survival when a bloodthirsty lion starts to stalk them.',
      poster_path: '/iRV0IB5xQeOymuGGUBarTecQVAl.jpg',
      media_type: 'movie',
      genre_ids: [Array],
      popularity: 1842.807,
      release_date: '2022-08-11',
      video: false,
      vote_average: 7.098,
      vote_count: 214
    },
    {
      adult: false,
      backdrop_path: '/tsYoljpKxjTBHLuPGySHeloGkv5.jpg',
      id: 773975,
      title: 'End of the Road',
      original_language: 'en',
      original_title: 'End of the Road',
      overview: 'Recently widowed mom Brenda fights to protect her family during a harrowing road trip when a murder and a missing bag of cash plunge them into danger.',
      poster_path: '/tLFIMuPWJHlTJ6TN8HCOiSD6SdA.jpg',
      media_type: 'movie',
      genre_ids: [Array],
      popularity: 121.491,
      release_date: '2022-09-09',
      video: false,
      vote_average: 6.986,
      vote_count: 71
    },
    {
      adult: false,
      backdrop_path: '/odJ4hx6g6vBt4lBWKFD1tI8WS4x.jpg',
      id: 361743,
      title: 'Top Gun: Maverick',
      original_language: 'en',
      original_title: 'Top Gun: Maverick',
      overview: 'After more than thirty years of service as one of the Navy’s top aviators, and dodging the advancement in rank that would ground him, Pete “Maverick” Mitchell finds himself training a detachment of TOP GUN graduates for a specialized mission the likes of which no living pilot has ever seen.',
      poster_path: '/62HCnUTziyWcpDaBO2i1DX17ljH.jpg',
      media_type: 'movie',
      genre_ids: [Array],
      popularity: 2501.524,
      release_date: '2022-05-24',
      video: false,
      vote_average: 8.362,
      vote_count: 3638
    },
    {
      adult: false,
      backdrop_path: '/7Y3LdmsZukXhmwxtO0UF95BFBTt.jpg',
      id: 682507,
      title: 'Where the Crawdads Sing',
      original_language: 'en',
      original_title: 'Where the Crawdads Sing',
      overview: 'Abandoned by her family, Kya raises herself all alone in the marshes outside of her small town. When her former boyfriend is found dead, Kya is instantly branded by the local townspeople and law enforcement as the prime suspect for his murder.',
      poster_path: '/n1el846gLDXfhOvrRCsyvaAOQWv.jpg',
      media_type: 'movie',
      genre_ids: [Array],
      popularity: 964.144,
      release_date: '2022-07-15',
      video: false,
      vote_average: 7.465,
      vote_count: 188
    },
    {
      adult: false,
      backdrop_path: '/fY6n7AeEUnQuSKbfAF2Ftd3Z6sG.jpg',
      id: 911129,
      title: 'No Limit',
      original_language: 'fr',
      original_title: 'Sous emprise',
      overview: "Roxana Aubrey decides to drop her studies and escape her life in Paris for a free diving course in the south of France. She is quickly pulled into a life that reaches new depths brought by the weight of an ocean's descent.",
      poster_path: '/fUdeneiMUQkE1Yb3Qx7dML0HVf.jpg',
      media_type: 'movie',
      genre_ids: [Array],
      popularity: 73.143,
      release_date: '2022-09-09',
      video: false,
      vote_average: 6.6,
      vote_count: 55
    },
    {
      adult: false,
      backdrop_path: '/2RSirqZG949GuRwN38MYCIGG4Od.jpg',
      id: 985939,
      title: 'Fall',
      original_language: 'en',
      original_title: 'Fall',
      overview: 'For best friends Becky and Hunter, life is all about conquering fears and pushing limits. But after they climb 2,000 feet to the top of a remote, abandoned radio tower, they find themselves stranded with no way down. Now Becky and Hunter’s expert climbing skills will be put to the ultimate test as they desperately fight to survive the elements, a lack of supplies, and vertigo-inducing heights.',
      poster_path: '/9f5sIJEgvUpFv0ozfA6TurG4j22.jpg',
      media_type: 'movie',
      genre_ids: [Array],
      popularity: 9423.858,
      release_date: '2022-08-11',
      video: false,
      vote_average: 7.507,
      vote_count: 437
    },
    {
      adult: false,
      backdrop_path: '/9JGS0O9wAr7c56VwSEPyeKT6Xac.jpg',
      id: 507086,
      title: 'Jurassic World Dominion',
      original_language: 'en',
      original_title: 'Jurassic World Dominion',
      overview: 'Four years after Isla Nublar was destroyed, dinosaurs now live—and hunt—alongside humans all over the world. This fragile balance will reshape the future and determine, once and for all, whether human beings are to remain the apex predators on a planet they now share with history’s most fearsome creatures.',
      poster_path: '/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg',
      media_type: 'movie',
      genre_ids: [Array],
      popularity: 2661.535,
      release_date: '2022-06-01',
      video: false,
      vote_average: 7.074,
      vote_count: 3293
    },
    {
      adult: false,
      backdrop_path: '/PSBUyz5jXYqKr2OvLhQWmTbmSx.jpg',
      id: 1015606,
      title: "Obi-Wan Kenobi: A Jedi's Return",
      original_language: 'en',
      original_title: "Obi-Wan Kenobi: A Jedi's Return",
      overview: 'A new documentary that showcases the making of the epic limited series. Features never-before-seen, behind-the-scenes footage, interviews and visits to the creature shop and props department.',
      poster_path: '/67wDFHNXkCa1PvaTZr6lT5YQKCm.jpg',
      media_type: 'movie',
      genre_ids: [Array],
      popularity: 222.083,
      release_date: '2022-09-08',
      video: false,
      vote_average: 8.1,
      vote_count: 27
    },
    {
      adult: false,
      backdrop_path: '/xVbppM1xgbskOKgOuV8fbWBWHtt.jpg',
      id: 762504,
      title: 'Nope',
      original_language: 'en',
      original_title: 'Nope',
      overview: 'Residents in a lonely gulch of inland California bear witness to an uncanny, chilling discovery.',
      poster_path: '/AcKVlWaNVVVFQwro3nLXqPljcYA.jpg',
      media_type: 'movie',
      genre_ids: [Array],
      popularity: 2214.008,
      release_date: '2022-07-20',
      video: false,
      vote_average: 7.04,
      vote_count: 1370
    },
    {
      adult: false,
      backdrop_path: '/xyS0NgcQ2pbGWcwvSSu3xKEBhoO.jpg',
      id: 614934,
      title: 'Elvis',
      original_language: 'en',
      original_title: 'Elvis',
      overview: 'The life story of Elvis Presley as seen through the complicated relationship with his enigmatic manager, Colonel Tom Parker.',
      poster_path: '/qBOKWqAFbveZ4ryjJJwbie6tXkQ.jpg',
      media_type: 'movie',
      genre_ids: [Array],
      popularity: 587.695,
      release_date: '2022-06-22',
      video: false,
      vote_average: 7.869,
      vote_count: 1421
    },
    {
      adult: false,
      backdrop_path: '/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg',
      id: 634649,
      title: 'Spider-Man: No Way Home',
      original_language: 'en',
      original_title: 'Spider-Man: No Way Home',
      overview: 'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.',
      poster_path: '/uJYYizSuA9Y3DCs0qS4qWvHfZg4.jpg',
      media_type: 'movie',
      genre_ids: [Array],
      popularity: 1401.809,
      release_date: '2021-12-15',
      video: false,
      vote_average: 8.042,
      vote_count: 15052
    },
    {
      adult: false,
      backdrop_path: '/nmGWzTLMXy9x7mKd8NKPLmHtWGa.jpg',
      id: 438148,
      title: 'Minions: The Rise of Gru',
      original_language: 'en',
      original_title: 'Minions: The Rise of Gru',
      overview: 'A fanboy of a supervillain supergroup known as the Vicious 6, Gru hatches a plan to become evil enough to join them, with the backup of his followers, the Minions.',
      poster_path: '/wKiOkZTN9lUUUNZLmtnwubZYONg.jpg',
      media_type: 'movie',
      genre_ids: [Array],
      popularity: 2566.579,
      release_date: '2022-06-29',
      video: false,
      vote_average: 7.653,
      vote_count: 1893
    },
    {
      adult: false,
      backdrop_path: '/vjnLXptqdxnpNJer5fWgj2OIGhL.jpg',
      id: 818397,
      title: 'Memory',
      original_language: 'en',
      original_title: 'Memory',
      overview: "Alex, an assassin-for-hire, finds that he's become a target after he refuses to complete a job for a dangerous criminal organization. With the crime syndicate and FBI in hot pursuit, Alex has the skills to stay ahead, except for one thing: he is struggling with severe memory loss, affecting his every move. Alex must question his every action and whom he can ultimately trust.",
      poster_path: '/4Q1n3TwieoULnuaztu9aFjqHDTI.jpg',
      media_type: 'movie',
      genre_ids: [Array],
      popularity: 810.239,
      release_date: '2022-04-28',
      video: false,
      vote_average: 7.226,
      vote_count: 755
    },
    {
      adult: false,
      backdrop_path: '/hYZ4a0JvPETdfgJJ9ZzyFufq8KQ.jpg',
      id: 629176,
      title: 'Samaritan',
      original_language: 'en',
      original_title: 'Samaritan',
      overview: 'Thirteen year old Sam Cleary  suspects that his mysteriously reclusive neighbor Mr. Smith is actually the legendary vigilante Samaritan, who was reported dead 20 years ago. With crime on the rise and the city on the brink of chaos, Sam makes it his mission to coax his neighbor out of hiding to save the city from ruin.',
      poster_path: '/vwq5iboxYoaSpOmEQrhq9tHicq7.jpg',
      media_type: 'movie',
      genre_ids: [Array],
      popularity: 5798.563,
      release_date: '2022-08-25',
      video: false,
      vote_average: 7.023,
      vote_count: 901
    },
    {
      adult: false,
      backdrop_path: '/rhIMDeJcYIlC0vgWFceh2B4sYuy.jpg',
      id: 894205,
      title: 'Werewolf by Night',
      original_language: 'en',
      original_title: 'Werewolf by Night',
      overview: 'On a dark and somber night, a secret cabal of monster hunters emerge from the shadows and gather at the foreboding Bloodstone Temple following the death of their leader. In a strange and macabre memorial to the leader’s life, the attendees are thrust into a mysterious and deadly competition for a powerful relic—a hunt that will ultimately bring them face to face with a dangerous monster.',
      poster_path: '/mvIvNKRIJPPS7WSFarFhOAGIVnU.jpg',
      media_type: 'movie',
      genre_ids: [Array],
      popularity: 2.288,
      release_date: '2022-10-07',
      video: false,
      vote_average: 0,
      vote_count: 0
    },
    {
      adult: false,
      backdrop_path: '/xfNHRI2f5kHGvogxLd0C5sB90L7.jpg',
      id: 539681,
      title: 'DC League of Super-Pets',
      original_language: 'en',
      original_title: 'DC League of Super-Pets',
      overview: 'When Superman and the rest of the Justice League are kidnapped, Krypto the Super-Dog must convince a rag-tag shelter pack - Ace the hound, PB the potbellied pig, Merton the turtle and Chip the squirrel - to master their own newfound powers and help him rescue the superheroes.',
      poster_path: '/r7XifzvtezNt31ypvsmb6Oqxw49.jpg',
      media_type: 'movie',
      genre_ids: [Array],
      popularity: 3493.847,
      release_date: '2022-07-27',
      video: false,
      vote_average: 7.607,
      vote_count: 500
    },
    {
      adult: false,
      backdrop_path: '/wcKFYIiVDvRURrzglV9kGu7fpfY.jpg',
      id: 453395,
      title: 'Doctor Strange in the Multiverse of Madness',
      original_language: 'en',
      original_title: 'Doctor Strange in the Multiverse of Madness',
      overview: 'Doctor Strange, with the help of mystical allies both old and new, traverses the mind-bending and dangerous alternate realities of the Multiverse to confront a mysterious new adversary.',
      poster_path: '/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg',
      media_type: 'movie',
      genre_ids: [Array],
      popularity: 1537.412,
      release_date: '2022-05-04',
      video: false,
      vote_average: 7.481,
      vote_count: 5672
    },
    {
      adult: false,
      backdrop_path: '/7ZO9yoEU2fAHKhmJWfAc2QIPWJg.jpg',
      id: 766507,
      title: 'Prey',
      original_language: 'en',
      original_title: 'Prey',
      overview: 'When danger threatens her camp, the fierce and highly skilled Comanche warrior Naru sets out to protect her people. But the prey she stalks turns out to be a highly evolved alien predator with a technically advanced arsenal.',
      poster_path: '/ujr5pztc1oitbe7ViMUOilFaJ7s.jpg',
      media_type: 'movie',
      genre_ids: [Array],
      popularity: 3659.907,
      release_date: '2022-08-02',
      video: false,
      vote_average: 7.967,
      vote_count: 3754
    }
  ];
  total_pages: 1000;
  total_results: 20000
}